version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/usr/src/app/src
      - ./nodemon.json:/usr/src/app/nodemon.json
    ports:
      - 3000:3000
  ws:
    container_name: ws_server
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/usr/src/app/src
      - ./nodemon.json:/usr/src/app/nodemon.json
    ports:
      - 8080:8080
  mongo:
    image: mongo:4.4.6
    ports:
      - "27017:27017"
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
